appname = casdoor
httpport = 8000
runmode = dev
copyfromorigin = true
driverName = sqlite
dataSourceName = /casdoor/casdoor.db
dbName = casdoor.db
dbHost =
dbPort = 3306
dbUser =
dbPassword =
dbName2 =
dbHost2 =
dbPort2 = 3306
dbUser2 =
dbPassword2 =
dbName3 =
dbHost3 =
dbPort3 = 3306
dbUser3 =
dbPassword3 =
initScore = 0
logPostOnly = true
origin = 
