/** Browser-safe syntax for the random invitation credential; validity is checked by CP. */
import { z } from 'zod';

export const INVITE_TOKEN_BYTES = 16;
export const MAX_INVITE_USES = 10_000;
const capacity = z.number().int().min(1).max(MAX_INVITE_USES);
export const CreateInviteSchema = z.object({ label: z.string().trim().max(64).optional(), maxUses: capacity.default(1) }).strict();
export const ExpandInviteSchema = z.object({ additionalUses: capacity }).strict();
export const InvitePublicSchema = z.object({
  id: z.string(), label: z.string().nullable(), createdBy: z.string(), createdAt: z.number(),
  revokedAt: z.number().nullable(), consumedAt: z.number().nullable(), consumedTenantId: z.string().nullable(),
  maxUses: capacity, usedCount: z.number().int().nonnegative(),
});
export type InvitePublic = z.infer<typeof InvitePublicSchema>;
export type InviteDataSchema<T> = z.ZodType<T>;
export const InviteLinkSchema = z.object({ link: z.string().url() });

/** 邀请接口响应的唯一解析入口；失败响应保留服务端真实错误。 */
export function parseInviteResponse<T>(value: unknown, dataSchema: InviteDataSchema<T>): T {
  const schema = z.discriminatedUnion('success', [
    z.object({ success: z.literal(true), data: dataSchema }),
    z.object({ success: z.literal(false), error: z.string() }),
  ]);
  const response = schema.parse(value);
  if (!response.success) throw new Error(response.error);
  return response.data;
}

/** 同源状态派生；消费时间保留首次归因，不再代表整条邀请失效。 */
export function inviteAvailability(invite: InvitePublic) {
  const remaining = Math.max(0, invite.maxUses - invite.usedCount);
  return { remaining, status: invite.revokedAt !== null ? 'revoked' as const : remaining === 0 ? 'exhausted' as const : 'available' as const };
}
const INVITE_TOKEN_PATTERN = new RegExp(`^[0-9a-f]{${INVITE_TOKEN_BYTES * 2}}$`);

/** Accept only credentials generated by CP, never a URL or a redirect target. */
export function isInviteToken(value: unknown): value is string {
  return typeof value === 'string' && INVITE_TOKEN_PATTERN.test(value);
}
