/** Browser-safe syntax for the random invitation credential; validity is checked by CP. */
export const INVITE_TOKEN_BYTES = 16;
const INVITE_TOKEN_PATTERN = new RegExp(`^[0-9a-f]{${INVITE_TOKEN_BYTES * 2}}$`);

/** Accept only credentials generated by CP, never a URL or a redirect target. */
export function isInviteToken(value: unknown): value is string {
  return typeof value === 'string' && INVITE_TOKEN_PATTERN.test(value);
}
